version: '3'
services:
  aws-cli:
    container_name: 'aws-cli'
    image: aws-s3/aws-cli/awsebcli
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true

    volumes:
    - .:/workspace:cached